version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  todo-app:
    image: mostafahu/todo-list-nodejs:v1
    container_name: todo-list
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    restart: always

volumes:
  mongo_data:

