apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: todo
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort  # أو LoadBalancer إذا كنت على Cloud

